[functions.process-client-welcome-drip]
verify_jwt = false
schedule = "0 * * * *" # run hourly; function sends only if due

[functions.schedule-client-welcome-drip]
verify_jwt = false


[functions.search-tracks]
enabled = true
verify_jwt = true
import_map = "./functions/search-tracks/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/search-tracks/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/search-tracks/*.html" ]
