-- Add comprehensive jazz synonyms
INSERT INTO search_synonyms (term, synonyms)
VALUES
  ('jazz', ARRAY['jazzy', 'smooth jazz', 'bebop', 'jazz fusion', 'lounge jazz', 'acid jazz', 'nu jazz', 'jazz funk', 'jazz rock', 'jazz blues', 'jazz pop', 'jazz hip hop', 'jazz electronic', 'jazz ambient', 'jazz chill', 'jazz lounge', 'jazz cafe', 'jazz club', 'jazz bar', 'jazz restaurant', 'jazz hotel', 'jazz spa', 'jazz yoga', 'jazz meditation', 'jazz relaxation', 'jazz background', 'jazz instrumental', 'jazz piano', 'jazz saxophone', 'jazz trumpet', 'jazz guitar', 'jazz bass', 'jazz drums', 'jazz vocals', 'jazz singer', 'jazz quartet', 'jazz trio', 'jazz ensemble', 'jazz orchestra', 'jazz big band']),
  ('jazzy', ARRAY['jazz', 'smooth jazz', 'bebop', 'jazz fusion', 'lounge jazz', 'acid jazz', 'nu jazz', 'jazz funk', 'jazz rock', 'jazz blues', 'jazz pop', 'jazz hip hop', 'jazz electronic', 'jazz ambient', 'jazz chill', 'jazz lounge', 'jazz cafe', 'jazz club', 'jazz bar', 'jazz restaurant', 'jazz hotel', 'jazz spa', 'jazz yoga', 'jazz meditation', 'jazz relaxation', 'jazz background', 'jazz instrumental', 'jazz piano', 'jazz saxophone', 'jazz trumpet', 'jazz guitar', 'jazz bass', 'jazz drums', 'jazz vocals', 'jazz singer', 'jazz quartet', 'jazz trio', 'jazz ensemble', 'jazz orchestra', 'jazz big band']),
  ('smooth jazz', ARRAY['jazz', 'jazzy', 'lounge jazz', 'jazz fusion', 'jazz ambient', 'jazz chill', 'jazz lounge', 'jazz cafe', 'jazz club', 'jazz bar', 'jazz restaurant', 'jazz hotel', 'jazz spa', 'jazz yoga', 'jazz meditation', 'jazz relaxation', 'jazz background', 'jazz instrumental', 'jazz piano', 'jazz saxophone', 'jazz trumpet', 'jazz guitar', 'jazz bass', 'jazz drums', 'jazz vocals', 'jazz singer', 'jazz quartet', 'jazz trio', 'jazz ensemble', 'jazz orchestra', 'jazz big band']),
  ('bebop', ARRAY['jazz', 'jazzy', 'jazz fusion', 'jazz funk', 'jazz rock', 'jazz blues', 'jazz pop', 'jazz hip hop', 'jazz electronic', 'jazz ambient', 'jazz chill', 'jazz lounge', 'jazz cafe', 'jazz club', 'jazz bar', 'jazz restaurant', 'jazz hotel', 'jazz spa', 'jazz yoga', 'jazz meditation', 'jazz relaxation', 'jazz background', 'jazz instrumental', 'jazz piano', 'jazz saxophone', 'jazz trumpet', 'jazz guitar', 'jazz bass', 'jazz drums', 'jazz vocals', 'jazz singer', 'jazz quartet', 'jazz trio', 'jazz ensemble', 'jazz orchestra', 'jazz big band']),
  ('jazz fusion', ARRAY['jazz', 'jazzy', 'smooth jazz', 'bebop', 'lounge jazz', 'acid jazz', 'nu jazz', 'jazz funk', 'jazz rock', 'jazz blues', 'jazz pop', 'jazz hip hop', 'jazz electronic', 'jazz ambient', 'jazz chill', 'jazz lounge', 'jazz cafe', 'jazz club', 'jazz bar', 'jazz restaurant', 'jazz hotel', 'jazz spa', 'jazz yoga', 'jazz meditation', 'jazz relaxation', 'jazz background', 'jazz instrumental', 'jazz piano', 'jazz saxophone', 'jazz trumpet', 'jazz guitar', 'jazz bass', 'jazz drums', 'jazz vocals', 'jazz singer', 'jazz quartet', 'jazz trio', 'jazz ensemble', 'jazz orchestra', 'jazz big band'])
ON CONFLICT (term)
DO UPDATE SET
  synonyms = EXCLUDED.synonyms;
