[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"

[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-DNS-Prefetch-Control = "off"
    X-Permitted-Cross-Domain-Policies = "none"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://js.stripe.com https://checkout.stripe.com https://maps.googleapis.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob: https://*.stripe.com https://maps.googleapis.com https://maps.gstatic.com https://img.youtube.com; media-src 'self' https: blob: https://*.supabase.co; connect-src 'self' https://*.supabase.co https://api.stripe.com https://checkout.stripe.com https://maps.googleapis.com https://accounts.spotify.com https://api.spotify.com https://www.google-analytics.com wss://*.supabase.co; frame-src 'self' https://js.stripe.com https://checkout.stripe.com https://www.google.com/recaptcha/ https://www.youtube.com https://youtube.com; object-src 'none'; base-uri 'self'; form-action 'self' https://checkout.stripe.com; frame-ancestors 'none'; upgrade-insecure-requests"

[[headers]]
  for = "/api/*"
  [headers.values]
    # Additional security for API endpoints
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/admin/*"
  [headers.values]
    # Stricter security for admin areas
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Security: Block access to sensitive files
[[redirects]]
  from = "/.env*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/package.json"
  to = "/404"
  status = 404

[[redirects]]
  from = "/pnpm-lock.yaml"
  to = "/404"
  status = 404

[[redirects]]
  from = "/node_modules/*"
  to = "/404"
  status = 404

# Rate limiting configuration
[context.production.environment]
  RATE_LIMIT_ENABLED = "true"
  RATE_LIMIT_MAX_REQUESTS = "100"
  RATE_LIMIT_WINDOW_MS = "60000"

[context.deploy-preview.environment]
  RATE_LIMIT_ENABLED = "true"
  RATE_LIMIT_MAX_REQUESTS = "50"
  RATE_LIMIT_WINDOW_MS = "60000" 

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 