   name: Trigger Insert White Label Monthly Payments

   on:
     schedule:
       - cron: '0 0 * * *'  # Every day at midnight UTC

   jobs:
     call-supabase-edge-function:
       runs-on: ubuntu-latest
       steps:
         - name: Call Supabase Edge Function
           run: |
             curl -X POST "https://yciqkebqlajqbpwlujma.supabase.co/functions/v1/insert_monthly_white_label_payments"

             